### PR TITLE
Add skip_configuration to CampaignManager

### PR DESCRIPTION
**Pull request by mattia-lecci**
This allows to manually configure the ns-3 repository allowing greater configuration flexibility (e.g., CXXFLAGS, disabling examples/tests, compile only some modules, etc.)

Please let me know if any additional code/fix/doc is needed.

### CODE REVIEW

**Comment by mattia-lecci** [comment]
any news on this?

**Comment by mattia-lecci** [comment]
ping

**Comment by tommasozugno** [comment]
@mattia-lecci is happy now

**Comment by DvdMgr** [comment]
Ping me enough times and I'll pay attention in the end!

Sorry for the delay :P

**Pull request merged**
